version: "3.7"

services:
  elixir:
    build: .
    working_dir: /home/elixir/app
    depends_on: 
      - neo4j
    volumes:
      - "./lib:/home/elixir/app/lib"
    ports:
      - "4000:4000"
    command: mix run --no-halt
  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./data:/data"